"""empty message

Revision ID: 1bef947c8f6a
Revises: 
Create Date: 2018-12-22 15:03:26.609254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bef947c8f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_room', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_student_student_id'), table_name='tb_student')
    op.alter_column('tb_major', 'major_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key('fk_course', 'tb_course_student', 'tb_course', ['course_id'], ['course_id'])
    op.create_foreign_key('fk_student', 'tb_course_student', 'tb_student', ['student_id'], ['student_id'])
    op.drop_index(op.f('ix_tb_course_student_student_id'), table_name='tb_course_student')
    op.drop_index(op.f('ix_tb_course_student_course_id'), table_name='tb_course_student')
    op.alter_column('tb_course_student', 'student_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_course_student', 'course_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_tb_course_course_id'), table_name='tb_course')
    op.drop_table('tb_teacher')
    op.drop_index(op.f('ix_tb_reservation_user_id'), table_name='tb_reservation')
    op.drop_index(op.f('ix_tb_reservation_class_id'), table_name='tb_reservation')
    op.drop_table('tb_reservation')
    op.drop_table('tb_class')
    # ### end Alembic commands ###
