"""empty message

Revision ID: e4a417621f8c
Revises: 1bef947c8f6a
Create Date: 2018-12-22 15:04:06.407665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4a417621f8c'
down_revision = '1bef947c8f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('jieshu', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tb_teacher', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_teacher', 'email')
    op.drop_index(op.f('ix_tb_student_student_id'), table_name='tb_student')
    op.alter_column('tb_major', 'major_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key('fk_student', 'tb_course_student', 'tb_student', ['student_id'], ['student_id'])
    op.create_foreign_key('fk_course', 'tb_course_student', 'tb_course', ['course_id'], ['course_id'])
    op.drop_index(op.f('ix_tb_course_student_student_id'), table_name='tb_course_student')
    op.drop_index(op.f('ix_tb_course_student_course_id'), table_name='tb_course_student')
    op.alter_column('tb_course_student', 'student_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tb_course_student', 'course_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_tb_course_course_id'), table_name='tb_course')
    op.drop_index(op.f('ix_tb_reservation_user_id'), table_name='tb_reservation')
    op.drop_index(op.f('ix_tb_reservation_class_id'), table_name='tb_reservation')
    op.drop_table('tb_reservation')
    # ### end Alembic commands ###
